#!/bin/bash
clear && printf '\e[3J'

echo "Corriendo tests...espere"
echo "|---------------------------------------------------------------------------------------|"
echo "|------------------------  INICIANDO TESTS LEXICO-SINTACTICOS  -------------------------|"
echo " ---------------------------------------------------------------------------------------"
echo "             --------------------------"
echo "            |---TESTS SATISFACTORIOS---|"
echo "             --------------------------"

for file in $(ls tests/lexico-sintacticos/ok); do
  echo "Ejecutando el test "$file""
  ./tests/tester "tests/lexico-sintacticos/ok/"$file
  sleep 3
  echo "-------------------------------------------------------"
done

sleep 3

echo "              ------------------------"
echo "             |-----TESTS FALLIDOS-----|"
echo "              ------------------------"

for file in $(ls tests/lexico-sintacticos/fail); do
  echo "Ejecutando el test "$file""
  ./tests/tester "tests/lexico-sintacticos/fail/"$file
  sleep 3
  echo "-------------------------------------------------------"
done

sleep 4

echo
echo
echo
echo "|-------------------------------------------------------------------------------|"
echo "|------------------------  INICIANDO TESTS SEMANTICOS  -------------------------|"
echo " -------------------------------------------------------------------------------"
echo "             --------------------------"
echo "            |---TESTS SATISFACTORIOS---|"
echo "             --------------------------"

for file in $(ls tests/semanticos/ok); do
  echo "Ejecutando el test "$file""
  ./tests/tester "tests/semanticos/ok/"$file
  sleep 3
  echo "-------------------------------------------------------"
done

sleep 4

echo "              ------------------------"
echo "             |-----TESTS FALLIDOS-----|"
echo "              ------------------------"

for file in $(ls tests/semanticos/fail); do
  echo "Ejecutando el test "$file""
  ./tests/tester "tests/semanticos/fail/"$file
  sleep 3
  echo "-------------------------------------------------------"
done

sleep 4

echo "|-------------------------------------------------------------------------------|"
echo "|------------------------  INICIANDO TESTS FINALES  -------------------------|"
echo " -------------------------------------------------------------------------------"

for file in $(ls tests/tests-finales); do
  echo "Ejecutando el test "$file""
  ./tests/tester "tests/tests-finales/"$file
  gcc -o test asm/assembler.s data/libaux.c
  ./test
  sleep 3
  echo "-------------------------------------------------------"
done